version: '3.1'
services:
  db_mysql:
    image: mysql:5.7
    ports:
        - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_HOST: localhost
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
